# Generated by Django 2.2.10 on 2020-02-18 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_message_room'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='is_goup',
            field=models.BooleanField(default=False),
        ),
    ]
